export const SIGNUP_INIT='SIGNUP_INIT';
export const SIGNUP_START='SIGNUP_START';
export const SIGNUP_SUCCESS='SIGNUP_SUCCESS';
export const SIGNUP_FAILED='SIGNUP_FAILED';

export const SIGNIN_INIT='SIGNIN_INIT';
export const SIGNIN_START='SIGNIN_START';
export const SIGNIN_SUCCESS='SIGNIN_SUCCESS';
export const SIGNIN_FAILED='SIGNIN_FAILED';
export const LOGOUT='LOGOUT';

export const FETCH_USER_DATA= 'FETCH_USER_DATA';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';

export const ADD_CATEGORIES_START = 'ADD_CATEGORIES_START';
export const ADD_CATEGORIES_SUCCESS = 'ADD_CATEGORIES_SUCCESS';
export const ADD_CATEGORIES_FAILED = 'ADD_CATEGORIES_FAILED';
export const ADD_CATEGORIES_INIT = 'ADD_CATEGORIES_INIT';

export const ADD_PRODUCT_START = 'ADD_PRODUCT_START';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAILED = 'ADD_PRODUCT_FAILED';
export const ADD_PRODUCT_INIT = 'ADD_PRODUCT_INIT';

export const FETCH_CATEGORIES_START = 'FETCH_CATEGORIES_START';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILED = 'FETCH_CATEGORIES_FAILED';

export const FETCH_PRODUCT_START = 'FETCH_PRODUCT_START';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAILED = 'FETCH_PRODUCT_FAILED';

export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';

export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAILED = 'DELETE_PRODUCT_FAILED';
export const DELETE_PRODUCT_START = 'DELETE_PRODUCT_START';

export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';

export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAILED = 'DELETE_CATEGORY_FAILED';
export const DELETE_CATEGORY_START = 'DELETE_CATEGORY_START';

export const CANCEL_FORM='CANCEL_FORM';

export const USER_INIT = 'USER_INIT';
export const ADD_TO_CART_START = 'ADD_TO_CART_START';
export const ADD_TO_CART_FAILED = 'ADD_TO_CART_FAILED';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';

export const REMOVE_FROM_CART_START = 'REMOVE_FROM_CART_START';
export const REMOVE_FROM_CART_FAILED = 'REMOVE_FROM_CART_FAILED';
export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS';

export const GET_CART_START = 'GET_CART_START';
export const GET_CART_FAILED = 'GET_CART_FAILED';
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';

export const CREATE_ORDER_START = 'CREATE_ORDER_START';
export const CREATE_ORDER_FAILED = 'CREATE_ORDER_FAILED';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_INIT = 'CREATE_ORDER_INIT';

export const CANCEL_ORDER_START = 'CANCEL_ORDER_START';
export const CANCEL_ORDER_FAILED = 'CANCEL_ORDER_FAILED';
export const CANCEL_ORDER_SUCCESS = 'CANCEL_ORDER_SUCCESS';

export const FETCH_ORDER_START = 'FETCH_ORDER_START';
export const FETCH_ORDER_FAILED = 'FETCH_ORDER_FAILED';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';

export const DELETE_ORDER_START = 'DELETE_ORDER_START';
export const DELETE_ORDER_FAILED = 'DELETE_ORDER_FAILED';
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';